[project]
name = "geoai"
version = "0.1.0"
description = "This is a Python package for GeoAI."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.12",
    "ollama>=0.4.8",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
